### ISSUE TITLE
能不能添加自定义背景的选项呢？🥰

### ISSUE THREAD

**Issue by KNQMuzzi** [festoney8/LiteLoaderQQNT-Telegram-Theme#1]
这个主题好棒！但是好像不能和自定义背景的插件一起使用，能不能添加一个自定义背景的选型呢？谢谢☆*: .｡. o(≧▽≦)o .｡.:*☆

**Comment by festoney8** [comment]
目前是可以自定义背景的，操作方法在Readme最后，目前换背景有一点麻烦，我试试在设置页面加一下手动选择图片

**Comment by KNQMuzzi** [comment]
好的ヽ(￣▽￣)و谢谢大佬

**Comment by festoney8** [comment]
已支持自定义背景
