### ISSUE TITLE
字体太大了

### ISSUE THREAD

**Issue by hacker-frok** [festoney8/LiteLoaderQQNT-Telegram-Theme#10]
字体太大了，作者应该是用的高分辨率显示器，在2K显示器上，字体大得如老人机一样...
建议调整为默认的字体，加大字体让用户通过配置实现

**Comment by festoney8** [comment]
能否提供截图，我看一下给哪里的字体增加配置项

**Comment by festoney8** [comment]
已在 v4.1.0 支持调节会话列表、编辑器文字字号，目前多数主要元素均可调节字号

**Comment by spacetimezero** [comment]
现在虽然可以调整字体和按钮的大小，但是这样一个个调整很难掌握一个合适的比例。
如果直接将QQNT的dpi设置修改为系统或系统(增强)虽然能够使比例恢复正常，但是字体会变得很模糊。
希望作者能够原生适配2k，谢谢！

**Comment by festoney8** [comment]
> 现在虽然可以调整字体和按钮的大小，但是这样一个个调整很难掌握一个合适的比例。 如果直接将QQNT的dpi设置修改为系统或系统(增强)虽然能够使比例恢复正常，但是字体会变得很模糊。 希望作者能够原生适配2k，谢谢！

DPI 相关问题很可能是插件解决不了的，这与系统缩放、显示器尺寸、显示器分辨率、软件 DPI 设置四个因素相关，可以试一下优化系统缩放与 DPI 设置，参考视频 https://www.bilibili.com/video/av319073138

**Comment by spacetimezero** [comment]
感谢回复，我的缩放比列是200%，之前已经尝试过修改 DPI 设置的三个选项，均没有效果，目前还是一个个调整大小先用着。歪个楼，在群聊中会显示头像而双人的对话中对方头像不显示，请问这是正常的吗，还是这也是 DPI 带来的问题。

**Comment by festoney8** [comment]
> 感谢回复，我的缩放比列是200%，之前已经尝试过修改 DPI 设置的三个选项，均没有效果，目前还是一个个调整大小先用着。歪个楼，在群聊中会显示头像而双人的对话中对方头像不显示，请问这是正常的吗，还是这也是 DPI 带来的问题。

对的，这是模仿 telegram 的特性，私聊双方不显示头像和昵称，群聊自己不显示头像和昵称

2K 显示器用 200% 缩放可能有一些问题，可以用 Aida64 软件查看显示器 PPI，配合上方视频中的表格计算适合的缩放

**Comment by spacetimezero** [comment]
#

> > 感谢回复，我的缩放比列是200%，之前已经尝试过修改 DPI 设置的三个选项，均没有效果，目前还是一个个调整大小先用着。歪个楼，在群聊中会显示头像而双人的对话中对方头像不显示，请问这是正常的吗，还是这也是 DPI 带来的问题。
> 
> 对的，这是模仿 telegram 的特性，私聊双方不显示头像和昵称，群聊自己不显示头像和昵称
> 
> 2K 显示器用 200% 缩放可能有一些问题，可以用 Aida64 软件查看显示器 PPI，配合上方视频中的表格计算适合的缩放

好像没什么用😹我的屏幕是 14.1 寸，在 2880x1800 分辨率下算出来 PPI 是 241 (https://dpi.lv/) ，根据这个计算得到 96*250%/241=0.996，结果设置了 250% 的缩放后再打开，按钮和字体比原来 200% 缩放下的还要大

**Comment by hacker-frok** [comment]
可能其实应该很简单，默认就按QQ官方的字体大小就行...
