### ISSUE TITLE
V4.1.0版本的一些小问题

### ISSUE THREAD

**Issue by xwxYa** [festoney8/LiteLoaderQQNT-Telegram-Theme#11]
①图片带文字时时间会歪；
②发送相同的透明图片有背景（聊天气泡）；
③未读消息气泡遮挡消息；
④tg中窗口的功能栏颜色与下方聊天栏上方的区域颜色是不一样的；
非常好的主题项目，期待后续更新🥰🥰

① 上下均为QQ
<img width="419" alt="图片带文字时时间会歪" src="https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/137683458/299106e7-4426-4f5e-9a7b-17dac2e82c54">
② 上下均为QQ
<img width="448" alt="相同的透明表情包有背景" src="https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/137683458/773f1b16-96c0-4d90-a467-58074c809556">
③&④ 上为QQ，下为tg
<img width="456" alt="未读消息气泡遮挡消息 上方颜色" src="https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/137683458/180f09ce-c028-498b-a4b8-25692a2f4215">

**Comment by festoney8** [comment]
1. 我认为这是轻量工具箱的适配问题，不使用tg主题时问题不明显，建议给轻量工具箱提 issue 询问这一情况。下图使用默认主题，可明显看出时间占用了一定高度。在图文混合气泡中，应使用 `inside-slot` 代替 `embed-slot`

![image](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/36254268/5690a0b5-7a70-4668-af74-8af2022ce577)

2. 将在近期修复

3. 气泡盖住文字是一个妥协，tg 主题支持将会话列表缩短到只剩下头像（仿 Telegram），此时气泡会显示在头像上方。这一功能不稳定，没有在 Readme 中注明（因为QQ新增的调节页面功能会让它失效）

4. 群名这里，QQ只有一行文字，无法模仿 Telegram 的两行效果。我会考虑把文字加粗和在线人数文字颜色优化一下让它更像

**Comment by xwxYa** [comment]
> 1. 我认为这是轻量工具箱的适配问题，不使用tg主题时问题不明显，建议给轻量工具箱提 issue 询问这一情况。下图使用默认主题，可明显看出时间占用了一定高度。在图文混合气泡中，应使用 `inside-slot` 代替 `embed-slot`
> 
> ![image](https://private-user-images.githubusercontent.com/36254268/306742443-5690a0b5-7a70-4668-af74-8af2022ce577.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NDMxMDMsIm5iZiI6MTcwODU0MjgwMywicGF0aCI6Ii8zNjI1NDI2OC8zMDY3NDI0NDMtNTY5MGEwYjUtN2E3MC00NjY4LWFmNzQtOGFmMjAyMmNlNTc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDE5MTMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhMjViOWViNGM4M2JjZWExYzRlNTY4ZjA1ZmNkZWU5YTg0NDA4ODIxYWQyNjE5Njc3MGY5M2QzMWNiYzZkMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M7nYeZKmoi_In4OHm09HRECoDlyINNsS93yjXHtGWbA)
> 
> 2. 将在近期修复
> 3. 气泡盖住文字是一个妥协，tg 主题支持将会话列表缩短到只剩下头像（仿 Telegram），此时气泡会显示在头像上方。这一功能不稳定，没有在 Readme 中注明（因为QQ新增的调节页面功能会让它失效）
> 4. 群名这里，QQ只有一行文字，无法模仿 Telegram 的两行效果。我会考虑把文字加粗和在线人数文字颜色优化一下让它更像

感谢答复，期待新版本(ﾟ∀ﾟ)人

**Comment by xwxYa** [comment]
> > 1. 我认为这是轻量工具箱的适配问题，不使用tg主题时问题不明显，建议给轻量工具箱提 issue 询问这一情况。下图使用默认主题，可明显看出时间占用了一定高度。在图文混合气泡中，应使用 `inside-slot` 代替 `embed-slot`
> > 
> > ![image](https://private-user-images.githubusercontent.com/36254268/306742443-5690a0b5-7a70-4668-af74-8af2022ce577.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NDMxMDMsIm5iZiI6MTcwODU0MjgwMywicGF0aCI6Ii8zNjI1NDI2OC8zMDY3NDI0NDMtNTY5MGEwYjUtN2E3MC00NjY4LWFmNzQtOGFmMjAyMmNlNTc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDE5MTMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhMjViOWViNGM4M2JjZWExYzRlNTY4ZjA1ZmNkZWU5YTg0NDA4ODIxYWQyNjE5Njc3MGY5M2QzMWNiYzZkMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M7nYeZKmoi_In4OHm09HRECoDlyINNsS93yjXHtGWbA)
> > 
> > 2. 将在近期修复
> > 3. 气泡盖住文字是一个妥协，tg 主题支持将会话列表缩短到只剩下头像（仿 Telegram），此时气泡会显示在头像上方。这一功能不稳定，没有在 Readme 中注明（因为QQ新增的调节页面功能会让它失效）
> > 4. 群名这里，QQ只有一行文字，无法模仿 Telegram 的两行效果。我会考虑把文字加粗和在线人数文字颜色优化一下让它更像
> 
> 感谢答复，期待新版本(ﾟ∀ﾟ)人

啊，非常抱歉，没认真看完你的答复就回应了(;´Д`)
第四点我想说的并不是群名称与人数（当然有也更好），而是...呃，抱歉我不太会描述，如图，是红框中两处颜色不同

图一图二为QQ与TG对比
<img width="456" alt="c8fbd8619cc86ed3f5d6bcfa0ccb1d24" src="https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/137683458/82601460-1123-470a-8242-618026be9282">
—
<img width="440" alt="c61e6621a27d147b011380447947cd9d" src="https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/137683458/61af61bf-d2f3-4eaf-9b75-405e4de7ad2a">

**Comment by festoney8** [comment]
第4点，QQ没有顶部那一行的元素，所以这个是模拟不出的

**Comment by xwxYa** [comment]
辛苦了😘

**Comment by xwxYa** [comment]
> 第4点，QQ没有顶部那一行的元素，所以这个是模拟不出的

好吧，我以为每个窗口上面那一栏都是单独的，辛苦😘

**Comment by festoney8** [comment]
已发布 v4.1.1 修复这些问题，有任何未修复的情况或其他bug请随时反馈
