### ISSUE TITLE
4.1.0遇到一些问题

### ISSUE THREAD

**Issue by boringye** [festoney8/LiteLoaderQQNT-Telegram-Theme#12]
1.如图红包下面会出现长的消息框
<img width="695" alt="{418E266F-E48E-47f8-8BB6-570F39149B28}" src="https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/121275187/a69e74df-271b-4deb-99eb-06ececf38412">
别人的表情包和自己的都会多出来消息框
<img width="702" alt="{656F6DE0-7639-42a6-BF2C-45282F764614}" src="https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/121275187/f8de203b-4556-4441-b598-2b72edc24972">
昨天设置调了下字号等设置没多大问题，但是今天后就发现有这个现象
2.有时候（重启无效）不在消息后面显示时间（昨天还可以，今天不行，今天没有动文件和设置）
3.每次启动QQ都会把之前默认的电报设置加载一边才会变成自己重新调整的，不可以直接加载好用户设置的吗？

**Comment by boringye** [comment]
如果可以，建议拉一个tg交流群方便交流沟通

**Comment by festoney8** [comment]
在liteloader官方tg群找我就可以，近期会发4.1.1更新修很多问题，其中包含你反馈的现象，其余情况等发版以后再交流

**Comment by festoney8** [comment]
已发布 v4.1.1，建议更新 Telegram 主题和轻量工具箱到最新版本，有任何未修复情况或其余bug请反馈

**Comment by boringye** [comment]
> 已发布 v4.1.1，建议更新 Telegram 主题和轻量工具箱到最新版本，有任何未修复情况或其余bug请反馈

好的，谢谢，能否分享下主页展示用的日间壁纸，我没有找到更合适的代替
![QQ截图20240221222931](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/121275187/5fafe4a5-7b8f-4932-a3d4-e3fed9fb18f1)

**Comment by festoney8** [comment]
> 好的，谢谢，能否分享下主页展示用的日间壁纸，我没有找到更合适的代替

https://www.pixiv.net/artworks/114660470

**Comment by festoney8** [comment]
关于启动QQ时载入的问题，tg主题在打开页面后覆盖QQ的样式，用户设定的样式覆盖tg主题的默认样式，有一个渲染的过程，v4.1.1中已优化了载入时间，但仍无法避免这一过程

**Comment by boringye** [comment]
> 关于启动QQ时载入的问题，tg主题在打开页面后覆盖QQ的样式，用户设定的样式覆盖tg主题的默认样式，有一个渲染的过程，v4.1.1中已优化了载入时间，但仍无法避免这一过程

已经体验过了，这个优化已经可以了，几乎肉眼不可见了

**Comment by boringye** [comment]
今天使用发现了一个bug，附上图
<img width="374" alt="{9F1EE3B0-F239-438a-8572-6B5A8A2B0098}" src="https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/121275187/ce7f875d-d8af-437a-ae9b-a21982df70ee">
就是发了一条信息文本过去后，在其他群聊中右键转发到刚刚聊天窗口的表情（文本没有试过）就会出现表情（在文本之后发出去的）跑到文本头上去

**Comment by festoney8** [comment]
> 发了一条信息文本过去后，在其他群聊中右键转发到刚刚聊天窗口的表情（文本没有试过）就会出现表情（在文本之后发出去的）跑到文本头上去

这个现象可以复现吗，能说一下如何具体步骤不

**Comment by boringye** [comment]
> > 发了一条信息文本过去后，在其他群聊中右键转发到刚刚聊天窗口的表情（文本没有试过）就会出现表情（在文本之后发出去的）跑到文本头上去
> 
> 这个现象可以复现吗，能说一下如何具体步骤不

是这样的，我在第一个群聊（称为A群吧）里面发了一个@人的文本消息后，然后换到另外一个群聊（B群）里面右键转发了一个表情包到第一个群聊（A群）里面，原本应该是表情包在我的消息下方显示，但是却跑到了我@人的文本消息上方了。上面的评论区有后缀时间可以看到，消息往上走了。我认为它是一个bug的存在（可能表达不是很清晰）

**Comment by festoney8** [comment]
我尝试这套操作没能复现这个问题，以及你的截图中，时间戳显示有些问题，请问用的是哪一版本的轻量工具箱？

**Comment by boringye** [comment]
> 我尝试这套操作没能复现这个问题，以及你的截图中，时间戳显示有些问题，请问用的是哪一版本的轻量工具箱？

仿电报皮肤是4.1.1，轻量工具箱我没用启用，时间显示我是用的QQ增强插件里面的，我的截图中时间戳显示，你应该是指的图片和文本时间错误就是我指的bug，我去尝试复现发现问题不存在了，但是我提交的时候确实发现了这个问题所在，很抱歉这次的匆忙提交，我会将版本更新至最新的4.1.4并停止QQ增强插件改用轻量工具箱去使用，如果再次碰到问题，我会复现一次会再反馈，很抱歉

**Comment by festoney8** [comment]
时间戳显示推荐用轻量工具箱的版本，因为我在Telegram主题中做过适配

**Comment by boringye** [comment]
> 时间戳显示推荐用轻量工具箱的版本，因为我在Telegram主题中做过适配

感谢你的推荐，我已经在使用了，因为我没注意到主题会更新这么快，希望在之后的版本中可以在设置中直接看到有更新提示，期待一下（因为插件商店也好像没办法检测到并且去直接更新）

**Comment by festoney8** [comment]
> 感谢你的推荐，我已经在使用了，因为我没注意到主题会更新这么快，希望在之后的版本中可以在设置中直接看到有更新提示，期待一下（因为插件商店也好像没办法检测到并且去直接更新）

新版的liteloader大概是不会增加插件管理功能了，插件商店不知道会不会做，因为普遍存在github连通性差的网络问题

想获取Release动态，建议用github的watch功能（就在star左边），选Custom模式，只勾选Releases，在项目有新版本发布时Github自动给你发邮件
