### ISSUE TITLE
希望能增加一个链接预览和自定义回复消息背景颜色功能

### ISSUE THREAD

**Issue by xwxYa** [festoney8/LiteLoaderQQNT-Telegram-Theme#13]
如题，虽然[QQ增强插件](https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-QQPromote/tree/master)有了该功能，但是不能自定义背景颜色，项目也存档了，所以想来这里球球qwq
图为使用了[QQ增强插件](https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-QQPromote/tree/master)的qq
<img width="788" alt="4a4440cc71783975117e8471a8b2ed0f" src="https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/137683458/bc494565-c64c-482a-8cfa-ecd6c323b946">

然后还想求个能自定义消息背景像tg那样
图为qq与tg的对比
<img width="457" alt="3009843608f4ee601d4bc3ea94f330e9" src="https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/137683458/343c501f-00e4-45a1-bc2a-459d15d27562">

**Comment by festoney8** [comment]
1. 不打算在主题内增加网络请求的代码，建议使用transitio插件给链接预览的背景改颜色，操作方法可在Liteloader群内询问

2. 考虑增加自定义回复消息高亮色功能，和Telegram一样，被回复的用户名是深色，回复背景是浅色

**Comment by xwxYa** [comment]
> 1. 不打算在主题内增加网络请求的代码，建议使用transitio插件给链接预览的背景改颜色，操作方法可在Liteloader群内询问
> 2. 考虑增加自定义回复消息高亮色功能，和Telegram一样，被回复的用户名是深色，回复背景是浅色

好的，感谢答复

**Comment by festoney8** [comment]
已发布 v4.1.3 新增回复背景色和高亮色调节

**Comment by festoney8** [comment]
v4.1.3 有些问题已撤下，发布了 v4.1.4
