### ISSUE TITLE
版本号在LiteLoaderQQNT界面显示不正常

### ISSUE THREAD

**Issue by xwxYa** [festoney8/LiteLoaderQQNT-Telegram-Theme#14]
如图，已更新至版本4.1.4，但在LiteLoaderQQNT界面显示的还是4.0.0
<img width="1057" alt="be0fccd2e6793e1dab72a77bc406b9f4" src="https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/137683458/684805f8-0c23-422d-94b7-7d4d9bd10a48">

**Comment by festoney8** [comment]
啊 我的锅，忘了改版本号XD，不单独修一次了，下次但愿我能记得
