### ISSUE TITLE
希望能有”回到原位置“以及”可以用侧键返回“的功能

### ISSUE THREAD

**Issue by xwxYa** [festoney8/LiteLoaderQQNT-Telegram-Theme#15]
抱歉，我可能描述得不是很准确，而且不太清楚qq的架构，不知道能不能实现
![录制_2024_02_23_23_13_02_254](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/137683458/9a63c474-1aa3-4559-bad8-6c0c3f405568)
![录制_2024_02_23_23_14_16_644](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/137683458/7bd13032-c8a5-4f9d-a442-4ba30a1518bb)

**Comment by festoney8** [comment]
1. 这是有可能做到的，但我目前不会写 XD

2. 鼠标侧键是通过宏定义形式实现的，不属于浏览器标准（单击双击左键右键），所以无法做到这个功能

**Comment by xwxYa** [comment]
加油！

**Comment by festoney8** [comment]
侧键返回在轻量工具箱已有实现
