### ISSUE TITLE
文件管理器UI问题

### ISSUE THREAD

**Issue by kanonmelodis** [festoney8/LiteLoaderQQNT-Telegram-Theme#16]
打开群文件之后1秒后文件列表会出现左侧缩进 出现左侧一大片空白界面
![image](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/20786161/575ebaf2-e526-40ee-b684-ac0f524bec50)

**Comment by festoney8** [comment]
已复现，待修复
