### ISSUE TITLE
【help wanted】消息内时间字体可以自定义吗

### ISSUE THREAD

**Issue by xwxYa** [festoney8/LiteLoaderQQNT-Telegram-Theme#17]
如图，左为tg，右为qq
<img width="416" alt="a878b6731482fe78d3b9bd96bcd270da" src="https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/137683458/273ba8ba-18c7-4d65-9d05-bef7564ebc43">

**Comment by festoney8** [comment]
我会将修改消息内时间的字号添加到主题设置内

字体可以用轻量工具箱或 transitio 修改

**Comment by xwxYa** [comment]
> 我会将修改消息内时间的字号添加到主题设置内
> 
> 字体可以用轻量工具箱或 transitio 修改

啊抱歉，我想说的就是字号( ﾟ∀。)

**Comment by festoney8** [comment]
已在 v4.1.6 支持修改消息内时间的字号
