### ISSUE TITLE
【help wanted】qq的时间可以实现tg这种效果吗？

### ISSUE THREAD

**Issue by xwxYa** [festoney8/LiteLoaderQQNT-Telegram-Theme#18]
如图为tg，向上滚动时当天时间会显示在消息框正中央，停止或向下滚动会自动消失，滚动至另一天自动切换

![录制_2024_02_26_22_12_03_593](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/137683458/d99bf2f0-9008-46ca-8918-09fc5aed28f2)

**Comment by festoney8** [comment]
Telegram 的日期在顶部吸附，是用来表示当前聊天都发生在这一天，而 QQ 的时间是几点几分，用来给用户提供时间信息

QQ 的时间和它下方的第一条消息是捆绑在一起的，即只有这条消息是这一时间发布

将时间固定在顶部没有功能性的意义，反而会带来歧义，因为它只是一个时间点，而不是时间段
