### ISSUE TITLE
【help wanted】qq是否能实现进入未读消息后自动回到退出时的位置

### ISSUE THREAD

**Issue by xwxYa** [festoney8/LiteLoaderQQNT-Telegram-Theme#21]
如图为tg与qq的对比
![录制_2024_03_09_10_33_43_537](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/137683458/a3cabe86-4b7a-4a2c-be58-24eceb4cf5f3)
![录制_2024_03_09_10_36_53_77](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/137683458/3eff6466-7793-47b4-8968-7f854c477623)

**Comment by festoney8** [comment]
基本很难实现

轻量工具箱有尝试 https://github.com/xiyuesaves/LiteLoaderQQNT-lite_tools/issues/145 ，可以试一下，但局限性很大

具体来说，QQ在切换聊天时会重置聊天列表，所以哪怕记录了上次聊天位置，也无法显示出来

**Comment by xwxYa** [comment]
原来如此，感谢

**Comment by QSlotus** [comment]
轻量工具箱的这个功能已经完成了
https://github.com/xiyuesaves/LiteLoaderQQNT-lite_tools/issues/145#issuecomment-1987586133
