### ISSUE TITLE
未来有打算优化一下消息渲染吗

### ISSUE THREAD

**Issue by boringye** [festoney8/LiteLoaderQQNT-Telegram-Theme#22]
我发现消息沉积的多了，用此主题上下查看消息会明显卡顿掉帧，未来有打算优化一下吗？

**Comment by festoney8** [comment]
好的，闲下来时我再测测性能看看能否优化一下

**Comment by festoney8** [comment]
预发布了 [v4.2.0](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/releases/tag/v4.2.0) 尝试优化了一下性能，测速上有提升但实际效果就不清楚了

比对方法：
1. 关闭全部其他 liteloader 插件，重启QQ，只使用旧版本 TG 主题，滑动消息看看性能
2. 升级 TG 主题到新版，并测试性能
3. 开启其他 liteloader 插件，并测试性能

**Comment by festoney8** [comment]
已在 v4.2.1 版本中多方面优化消息列表性能
