### ISSUE TITLE
[bug] QQ群成员无法隐藏

### ISSUE THREAD

**Issue by bd-dxg** [festoney8/LiteLoaderQQNT-Telegram-Theme#23]
我留意到QQ群的成员无法隐藏了,我习惯于隐藏掉QQ群成员列表,更多的位置留给信息展示,希望TG主题能修复一下这个功能

同时注意到 虽然主题支持了字体大小和颜色的修改, 但好像没看到设置不同字体的功能, 如果能加载本地字体的话就更好了

![image](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/34816426/de7e857f-ee68-48d6-bd3c-05c1e076dcab)

感谢大佬开发的组件

**Comment by festoney8** [comment]
1. 修改字体请使用[轻量工具箱](https://github.com/xiyuesaves/LiteLoaderQQNT-lite_tools)
2. 我在21484版本没能复现QQ群的成员无法隐藏的现象，把鼠标放在聊天区域右边框中间，有个隐藏按钮会显示出来，此时鼠标会变成手的样子，点这个按钮就可以展开/收起群成员

**Comment by bd-dxg** [comment]
> 1. 修改字体请使用[轻量工具箱](https://github.com/xiyuesaves/LiteLoaderQQNT-lite_tools)
> 2. 我在21484版本没能复现QQ群的成员无法隐藏的现象，把鼠标放在聊天区域右边框中间，有个隐藏按钮会显示出来，此时鼠标会变成手的样子，点这个按钮就可以展开/收起群成员

![image](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/34816426/5e844dca-4132-4602-a377-3dc1a83e3ca2)

这是我的QQ版本, 早上测试了确实没找到隐藏QQ群成员的位置, 麻烦确认一下

**Comment by festoney8** [comment]
我升级到了21804，没能复现

请问你的QQ鼠标放在这个位置有没有一个隐藏的小箭头出现？
![image](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/36254268/4be6dd90-c230-45ab-bb5a-8050b219f728)

**Comment by bd-dxg** [comment]
我重新安装了插件, 现在又有了 目前是深色模式 可能看的清楚一些 浅色模式完全没注意到箭头的存在, 或许这是一个需要优化的地方, 但问题已经解决了  不好意思

**Comment by festoney8** [comment]
将在下一版本突出显示这个箭头
