### ISSUE TITLE
怎样设置可以使背景色生效呢

### ISSUE THREAD

**Issue by KiwiR1der** [festoney8/LiteLoaderQQNT-Telegram-Theme#25]
按照Tg改了一个暗色模式，各配置项都挺好用的，但是到了背景色这里这个壁纸怎样才能丢失让背景色生效呢，壁纸那里除了选择图片没有置空的选项啊，只能添加一张深色背景了吗
![image](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/73887119/0e4774b2-5c92-4947-95ad-c89d2d1d5dbc)

**Comment by festoney8** [comment]
TG主题自带夜间模式，不需要调，只需要把 QQ 官方的主题设定改成夜间模式就可以，主题会自动切换的

夜间模式和日间模式分别使用两个壁纸，互相不干扰

**Comment by KiwiR1der** [comment]
哦~，原来如此，还在疑惑模式切换没有给开关哈哈😄
