### ISSUE TITLE
自定义输入框按钮的显示与隐藏

### ISSUE THREAD

**Issue by Reverier-Xu** [festoney8/LiteLoaderQQNT-Telegram-Theme#26]
如图，在轻量工具箱中有输入框图标精简设置，但是并不起效，能否在主题设置内也提供类似的精简选项？

![image](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/41937333/578dedb5-fbec-4bc7-8760-a3b622f6c498)

**Comment by festoney8** [comment]
请提供QQNT的版本与轻量工具箱的版本
图中的功能应是正常生效的，若失效可以给工具箱提issue反馈适配问题，telegram主题内暂不考虑做重复的管理功能

**Comment by Reverier-Xu** [comment]
QQNT: 3.2.7-22578
LiteLoader: 1.0.3
工具箱: 2.21.2

![image](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/41937333/e55783e8-ac1e-4bee-a020-cf90a26c2690)

修改设置后已经重启过QQ

我关掉主题再试试，谢谢
