### ISSUE TITLE
窗口最大化后，无法正常显示"群应用" 菜单

### ISSUE THREAD

**Issue by cntvc** [festoney8/LiteLoaderQQNT-Telegram-Theme#27]
如图，在窗口最大化后，"群应用" 菜单展开后会向右侧偏移到屏幕外

<img width="143" alt="Snipaste_2024_04_10_21_59_32" src="https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/119989194/f62a4e83-b0a5-4c31-ae12-fcd1f505cff8">

---

QQ: 9.9.9-22578
插件版本: 4.2.3
LiteLoder: 1.1.1

**Comment by festoney8** [comment]
已发布 v4.2.4 修复
