### ISSUE TITLE
设置里下拉列表选项文本框不显示文本

### ISSUE THREAD

**Issue by Rem0rs** [festoney8/LiteLoaderQQNT-Telegram-Theme#3]
如图
![1](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/139387223/97ef3ffa-d6b6-4a39-a309-eca86f2ec812)

同时也会导致其他插件的config界面的字体出现问题
![2](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/139387223/2b66d724-7ab8-4a21-b0d7-be8ac6cfd9d9)

**Comment by festoney8** [comment]
已修复该问题
