### ISSUE TITLE
[bug] v4.2.6的壁纸设定无效

### ISSUE THREAD

**Issue by YrracOwl** [festoney8/LiteLoaderQQNT-Telegram-Theme#30]
### 安装的插件
- [插件列表查看v1.1.0](https://github.com/ltxhhz/LL-plugin-list-viewer/tree/main)
- [轻量工具箱v3.28.8](https://github.com/xiyuesaves/LiteLoaderQQNT-lite_tools/tree/v4)
- 本插件v4.2.6

### BUG现象
*没有*开启轻量工具箱的「背景调整」，设置本插件的壁纸，无论是修改图片还是修改背景色，均无效，保持的背景色为 `#e8e8e8`

**Comment by festoney8** [comment]
请问操作系统和当前QQNT版本是什么

设置中除修改壁纸、修改背景色之外，其他功能是否可用？

**Comment by YrracOwl** [comment]
> 请问操作系统和当前QQNT版本是什么
> 
> 设置中除修改壁纸、修改背景色之外，其他功能是否可用？

- 操作系统版本
> 版本	Windows 11 专业版
> 版本	23H2
> 安装日期	‎2023/‎2/‎25
> 操作系统版本	22631.3593
> 体验	Windows Feature Experience Pack 1000.22700.1003.0

- QQ NT版本
> 9.9.9-23159

![image](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/37571668/79d91fcc-e4b6-40cc-a552-4bb62c19ae33)

除「修改壁纸」「修改背景色」以外，目前使用到的功能均可用。

**Comment by festoney8** [comment]
我使用相同版本 QQ 和插件没能复现，并且 `#e8e8e8` 这一颜色在 tg 主题的中并未使用到，很玄学

**请测试两个功能：**

1. 轻量工具箱的壁纸功能是否正常？

2. 禁用其他插件，仅开启 tg 主题，重启 QQ 后现象是否仍然存在？

---

若仍未恢复，麻烦安装插件 https://github.com/mo-jinran/chii-devtools

按 F12 查看 body 元素的样式，`--tg-container-image` 这一项是否正常，如下图

![image](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/36254268/4dd5910d-7f88-4d29-9c41-e0377c5756ba)

**Comment by YrracOwl** [comment]
> 我使用相同版本 QQ 和插件没能复现，并且 `#e8e8e8` 这一颜色在 tg 主题的中并未使用到，很玄学
> 
> **请测试两个功能：**
> 
> 1. 轻量工具箱的壁纸功能是否正常？
> 2. 禁用其他插件，仅开启 tg 主题，重启 QQ 后现象是否仍然存在？
> 
> 若仍未恢复，麻烦安装插件 https://github.com/mo-jinran/chii-devtools
> 
> 按 F12 查看 body 元素的样式，`--tg-container-image` 这一项是否正常，如下图
> 
> ![image](https://private-user-images.githubusercontent.com/36254268/332458896-4dd5910d-7f88-4d29-9c41-e0377c5756ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMDQxNjcsIm5iZiI6MTcxNjMwMzg2NywicGF0aCI6Ii8zNjI1NDI2OC8zMzI0NTg4OTYtNGRkNTkxMGQtN2Y4OC00ZDI5LTljNDEtZTAzNzdjNTc1NmJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDE1MDQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmNTQ0Y2FkOGI2YjgyY2U3Y2RjNmYyNjNhZTE1YTM2OGU5ZWFkYjMzYTJmODA0ZDgzNjA1NDZkYzE2OGMwM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eRslCTvXeyP-qhh0PROmCeXLItT7SyhNZZSvIvnXDbY)

破案了，要修改she设置里面的「超级调色盘」，点一下最上面那个「恢复默认」的按钮，然后不管是「轻量工具箱」的背景设置还是本插件的背景设置就都有效了；

感觉像是QQNT的这个逻辑最后把它覆盖了，不知道在它代码的哪一段，看看能不能修复一下。

![image](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/37571668/15b181d8-1fb3-44f6-afa0-a55dd9b4bce8)

**Comment by festoney8** [comment]
调色盘的壁纸在 tg 主题壁纸 / 工具箱壁纸 的上层，完全盖住，但这也让会员壁纸和插件共用成为了可能，我在 Readme 增加提示吧
