### ISSUE TITLE
[Bug]回复时，图文混排时出现的排版问题

### ISSUE THREAD

**Issue by KJH-x** [festoney8/LiteLoaderQQNT-Telegram-Theme#32]
| Question | Comparison |
| -------- | -------- |
| <img width="531" alt="截图_20240531151608" src="https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/53437291/548598fc-3bc0-48dd-a86c-60dceb2476c4"> |<img width="525" alt="截图_20240531152038" src="https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/53437291/e5135d68-e499-4c92-be55-63711aa992e8"> |

回复时表情包/图片+(足以使气泡达到最宽长度的)长段文字会形成如上图所示：

1. 回复气泡的两侧padding，上下padding均出现问题
2. [可选] 能不能增加一个选项把图片左对齐（毕竟文字也是左对齐的，看起来和谐点，不过问题不大）

此问题对于发送者和接收者均存在
感谢开发者🌹

**Comment by festoney8** [comment]
下图这种样式吗？感觉回复小图时确实好看了些，右侧有点过于空，待我把 telegram 的限制消息泡宽度也借鉴过来

![image](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/36254268/3cdb3f3b-4757-45d1-807a-9d02ab97e73a)

**Comment by KJH-x** [comment]
是滴，谢谢~（相比于下述完全模仿，我其实更喜欢您给出的这个方案）
如果追求模仿Telegram的话，长文字图片（有无回复不影响）似乎是嵌入缩放的感觉（在限制范围（上下限）内气泡高度随动，而宽度为定值）
| 都够大 | 不够长不够宽 |太长够宽 |够长太宽|
| -------- | -------- |-------- |-------- |
|<img width="339" alt="截图_20240601085904" src="https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/53437291/09ae6e0d-4328-4886-8fc2-e8b5c9b1b1c0">| <img width="347" alt="截图_20240601085837" src="https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/53437291/1faa3c68-4ba7-43bb-8458-5ca28d0cc2ce">|<img width="333" alt="截图_20240601085920" src="https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/53437291/afcd7154-afd7-4be5-a87e-d335cad9879d">|<img width="347" alt="截图_20240601090100" src="https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/53437291/50648159-aced-4e43-94b3-babf941e949c"> |

**Comment by festoney8** [comment]
长文字图片 确实是一个新的问题，如果回复内容图片左对齐，普通的图文内容是否保留居中对齐？

Telegram 的风格是图片和消息泡无间距，如果左对齐，长文字气泡会变成图 1 的奇怪样子

![image](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/36254268/ca035d72-82ad-454e-9acf-d87a1eaa06a1)

**Comment by KJH-x** [comment]
第一感觉上我会觉得下面的这种图片填满（以图片宽度代替长文字宽度？）的更佳
图一确实挺怪的

**Comment by festoney8** [comment]
> 第一感觉上我会觉得下面的这种图片填满（以图片宽度代替长文字宽度？）的更佳 图一确实挺怪的

可以做到，大图没问题，小图表情包+文字的情况就做不到填满了，否则一行只有两三个字，这种我会限制一下最低宽度保证可读性

**Comment by festoney8** [comment]
已上传预发布 https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/releases/tag/v4.3.0 ，试一下现在的样式如何

**Comment by KJH-x** [comment]
不好意思有点忙回复的晚了，目前我最开始提出的问题解决了，谢谢
补充：附图：
<img width="719" alt="截图_20240604123159" src="https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/53437291/1df4feb1-41a0-4e8c-8b18-3f92fec326c1">
