### ISSUE TITLE
群语音的头像覆盖有一定的变形错位问题

### ISSUE THREAD

**Issue by CSZCTZY** [festoney8/LiteLoaderQQNT-Telegram-Theme#35]
当使用群语音时，对应群的头像上会有一个覆盖图片，使用主题的情况下这个图片变扁了，导致有一定的错位
错误图片：![PixPin_2024-06-12_01-39-01](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/39491830/07b1b179-56ce-4ab2-8667-704034f5dafb)
原版正确图片：
![PixPin_2024-06-12_01-40-59](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/39491830/16732dfc-1e28-402c-b0b6-8fd1f877c120)

**Comment by festoney8** [comment]
已复现，将在下一版本修复

**Comment by CSZCTZY** [comment]
> 已复现，将在下一版本修复

想请教一下，如何单独调整合并转发消息中的消息间距，我发现转发消息中的消息间距和普通群聊中的不一致

**Comment by festoney8** [comment]
已发布 [v4.3.1](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/releases/tag/v4.3.1) 修复此问题
