### ISSUE TITLE
[bug] QQNT 9.9.11-24616下壁纸设置失效了

### ISSUE THREAD

**Issue by YrracOwl** [festoney8/LiteLoaderQQNT-Telegram-Theme#36]
QQNT 9.9.11-24616下壁纸设置失效了，在「超级调色盘」里点击「恢复默认」后 #30  ，壁纸设置仍然无效。

**Comment by festoney8** [comment]
已复现，24616的改动很多，近期会做适配，可以暂时回退到 9.9.11.24402 使用主题

**Comment by YrracOwl** [comment]
好的，感谢

**Comment by festoney8** [comment]
试一下 https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/releases/tag/v4.3.1 对 24616 的适配如何？稳定后就发新版

**Comment by YrracOwl** [comment]
在4.3.1下，目前我这里可以修改壁纸了

**Comment by festoney8** [comment]
修了一些其他 bug，已正式发布 [v4.3.1](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/releases/tag/v4.3.1)
