### ISSUE TITLE
[bug]好友列表置顶显示问题

### ISSUE THREAD

**Issue by WrunDorry** [festoney8/LiteLoaderQQNT-Telegram-Theme#37]
好友列表，若添加聊群/好友为置顶，鼠标移动至其上，没有和没有置顶好友/群聊按钮一样的阴影
如下图，放上去有阴影
![image](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/123614437/ab67cb84-f9a5-43de-8480-698bab09990f)
如下图，置顶群聊/好友鼠标放上去无阴影效果
![image](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/123614437/a207bdcf-2296-4533-9cd9-d3f763153db7)

**Comment by festoney8** [comment]
已发布 [v4.3.1](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/releases/tag/v4.3.1) 修复此问题
