### ISSUE TITLE
请求新主题[momotalk]

### ISSUE THREAD

**Issue by fatinghenji** [festoney8/LiteLoaderQQNT-Telegram-Theme#4]
https://github.com/makipom/MomoTalk-Telegram

**Comment by festoney8** [comment]
可以在主题设置自行调节颜色实现定制 MomoTalk-Telegram 这一主题风格

具体需要调节左边栏背景色 聊天气泡 聊天文字 列表栏背景 列表栏选中色 列表栏消息提示泡 这几项的颜色
所需颜色可以用截图软件Snipaste的取色器在telegram主题内提取

**Comment by fatinghenji** [comment]
我完全不会代码（能给出一些示例吗？

**Comment by festoney8** [comment]
完全不需要写代码
插件是有自己的设置页面的，在liteloader的列表栏里，在设置页面里用可视化界面修改颜色即可
![image](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/36254268/c98810e9-d1f0-43ed-9995-570364130f89)
