### ISSUE TITLE
无法显示聊天输入框！【已修复】

### ISSUE THREAD

**Issue by llkj0001** [festoney8/LiteLoaderQQNT-Telegram-Theme#44]
版本信息
![image](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/114677240/d36d388c-3863-4a4c-9095-979985561d3e)

![image](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/114677240/848c4743-77bd-4781-94a0-8b481d6b6d4e)

问题描述：
![image](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/114677240/465b5d07-f744-4e09-a79e-b58e2b34cbac)
如图所示，所有配置均默认，无法正常显示聊天输入框

**Comment by festoney8** [comment]
使用相同版本 QQ 并未复现

能否测试一下，关闭其他插件，只开启 TG 主题，重启 QQ 是否仍出现这一现象？

**Comment by llkj0001** [comment]
![image](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/114677240/1e5eafc6-2353-44c7-bcf7-2fd5a5e139c5)
仅开了一个LiteLoaderQQNT-Telegram-Theme，其他全关了

![image](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/114677240/a4082724-75ec-4081-ad18-f8a6ea700c50)
无效！

**Comment by festoney8** [comment]
是怎么恢复的，什么原因啊？
