### ISSUE TITLE
置顶会话背景色

### ISSUE THREAD

**Issue by zhr-nmlk** [festoney8/LiteLoaderQQNT-Telegram-Theme#45]
希望置顶会话的默认背景色可以换为rgb(40, 42, 55)，使这个主题更完美。

**Comment by festoney8** [comment]
主题的默认颜色完全复刻 TG 配色，所以默认不会突出显示置顶，并在设置里预留了配置，修改配色按照个人爱好 DIY 就好了

![image](https://github.com/user-attachments/assets/574da766-9589-4725-9bb4-16c57b0955bb)

**Comment by zhr-nmlk** [comment]
tg里面的置顶会话与其他会话颜色有区别的……

**Comment by festoney8** [comment]
win10 官方 TG 默认亮色暗色主题，没有区别的

![image](https://github.com/user-attachments/assets/5acad9f0-be60-40c0-8f51-bf2a68368a30)
![image](https://github.com/user-attachments/assets/a143ece2-2264-4200-9305-fd5c516d0582)
