### ISSUE TITLE
[Bug]发送图文混合消息的时候文字错位

### ISSUE THREAD

**Issue by html5syt** [festoney8/LiteLoaderQQNT-Telegram-Theme#46]
如图：
![image](https://github.com/user-attachments/assets/caaa66c3-40e2-4d86-92ad-9f47c2880017)
可以明显的看出此时文字的左间距为0，左下角文字被挡住。尝试寻找可能出问题的地方，但是我太菜了，没找到qwq
希望作者能修改一下，谢谢。
（这主题真的很像TG欸（（

**Comment by festoney8** [comment]
请提供一下版本信息截图，截这里，以及使用的 TG 主题的版本

![image](https://github.com/user-attachments/assets/8738caf5-0319-48b5-a1de-6c588380ad5c)

正常的样式是这样

![image](https://github.com/user-attachments/assets/7c355ad3-bb71-43a9-9bf6-676211699db3)

在图片上下都有文字时，会出现这一情况，这是已知的问题，并且非常难修就搁置了（这种情况不多见），但普通图文气泡不会出现这一现象，需要复现

![image](https://github.com/user-attachments/assets/07d5e13e-c8c3-49f6-b7cb-0e4e376e525d)

**Comment by html5syt** [comment]
![image](https://github.com/user-attachments/assets/eac29176-5ff7-4bc8-8471-97d1e1428803)
![image](https://github.com/user-attachments/assets/4f0e8a02-184d-4e48-abea-2186ea10c27c)
另外这是我的自定义CSS：
```
#app > div.container > div.draggable-view__container.sidebar > nav > div > div.sidebar__upper > div.nav.sidebar__nav > div:nth-child(5){
    display: none;
}
#app > div.container > div.draggable-view__container.sidebar > nav > div > div.sidebar__upper > div.nav.sidebar__nav > div:nth-child(3){
    display: none;
}
#app > div.container > div.draggable-view__container.sidebar > nav > div > div.sidebar__upper > div.nav.sidebar__nav > div.nav-item.nav-item-more{
    display: none;
}
#app > div.container > div.draggable-view__container.sidebar > nav > div > div.sidebar__lower > div > div:nth-child(1){
    display: none;
}
#app .aio .group-panel .group-chat .chat-input-area .msg-input .qq-editor .ck-editor .ck-editor__main .ck-content .ck-placeholder:before {
    --qq-editor-placeholder: "输入消息...";
}
#app > div.container > div.tab-container > div > div > div.two-col-layout__main > div > div.group-panel.need-token-updated > div.group-box__container > div > div.group-box__toggle{
    display: none;
}
```
这种是上下都有文字的情况：
![image](https://github.com/user-attachments/assets/b7161bf9-91f1-4de1-9431-f181ee0e6dd4)

**Comment by html5syt** [comment]
这是所有的插件列表：
![image](https://github.com/user-attachments/assets/5d9e8ea6-076d-4651-8d3e-edc450ae9654)
![image](https://github.com/user-attachments/assets/ae9736ac-0804-4996-bb11-b5bd37f7d652)
![image](https://github.com/user-attachments/assets/9fb9942c-8a0c-4fc8-90be-3eda3846997a)

**Comment by festoney8** [comment]
已确认是 markdown-it 插件将消息结构修改导致的现象，如图

由于 markdown 渲染后的 HTML 中文字内容没有标签包裹，我这里大概做不了适配

PS：TG 主题普通文字气泡圆角样式也会受 markdown 插件影响

![image](https://github.com/user-attachments/assets/586049da-a541-47de-b1cb-2c4e04aeabf8)

**Comment by html5syt** [comment]
好的，感谢作者咕~
