### ISSUE TITLE
群聊语音有覆盖头像的变形错位

### ISSUE THREAD

**Issue by ghostlemon** [festoney8/LiteLoaderQQNT-Telegram-Theme#48]
如图所示
![fa702731-7236-48b5-8ec2-09e689ef0aa8](https://github.com/user-attachments/assets/176d5ce8-2689-410b-b3e6-ffa596c73255)

主题版本号4.4.5

**Comment by festoney8** [comment]
已在 [v4.4.6](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/releases/tag/v4.4.6) 修复
