### ISSUE TITLE
聊天信息bug

### ISSUE THREAD

**Issue by HKRreimu** [festoney8/LiteLoaderQQNT-Telegram-Theme#51]
当Q群有相同群昵称的用户时候，两个人发的信息会被归为同一个人发送

**Comment by festoney8** [comment]
将在下一版本修复

**Comment by festoney8** [comment]
已在 [v4.4.7](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/releases/tag/v4.4.7) 修复
