### ISSUE TITLE
启动显示bug

### ISSUE THREAD

**Issue by lstzys** [festoney8/LiteLoaderQQNT-Telegram-Theme#52]
1.每次启动都会如下显示（显示不全，只有重新点下一QQ纯享模式的侧边栏才能正常显示）：
![主题bug](https://github.com/user-attachments/assets/04bf073b-0fb1-4395-933e-62b5e3d57a2b)
2.下拉聊天栏到最下面，也会触发显示不全的BUG：
![PixPin_2024-10-01_20-07-58](https://github.com/user-attachments/assets/a355a1ce-dee8-4f5a-8f6b-1726b711f562)

**Comment by festoney8** [comment]
第一个问题将在下一版修复

第二个问题没能复现，请问只开启本插件时，是否会出现这一情况？

**Comment by festoney8** [comment]
已在 [v4.4.7](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/releases/tag/v4.4.7) 修复启动时单双列的显示问题，未发现聊天栏下方显示异常问题

**Comment by lstzys** [comment]
> 第一个问题将在下一版修复
> 
> 第二个问题没能复现，请问只开启本插件时，是否会出现这一情况？

偶尔出现 我也不知道怎么复现出来的  不过显示错误的确是主题包的问题

**Comment by lstzys** [comment]
> 第一个问题将在下一版修复
> 
> 第二个问题没能复现，请问只开启本插件时，是否会出现这一情况？

我测试了一下，将主面板拉长再拉短，然后疯狂下滑滚轮，就会出现断一截的情况
![PixPin_2024-10-13_00-41-25](https://github.com/user-attachments/assets/3b7628bb-2186-4bcc-8b74-d246305f3a25)
![PixPin_2024-10-13_00-42-14](https://github.com/user-attachments/assets/88d76343-98d8-475d-8cb7-99a7359555b8)

**Comment by festoney8** [comment]
> > 第一个问题将在下一版修复
> > 第二个问题没能复现，请问只开启本插件时，是否会出现这一情况？
> 
> 我测试了一下，将主面板拉长再拉短，然后疯狂下滑滚轮，就会出现断一截的情况

还是没能复现，我这里不管怎么滚动都是正常的，看起来影响不大就先保持这样吧
