### ISSUE TITLE
气泡颜色修改不生效

### ISSUE THREAD

**Issue by ArcherLionheart** [festoney8/LiteLoaderQQNT-Telegram-Theme#53]
![image](https://github.com/user-attachments/assets/0c58fe71-ce76-4e9c-b4b2-3ec22971d247)
![image](https://github.com/user-attachments/assets/722252c0-ccaa-40bd-8482-ad120d192057)

**Comment by festoney8** [comment]
我这里没能复现，请提供一下下列信息：操作系统、QQ 版本、Telegram主题版本

可以测试一下，在 LIteloader 里只启用本主题，不启用其他插件时，是否会出现这一现象

**Comment by ArcherLionheart** [comment]
感谢提醒，经测试发现是与该插件冲突，关闭后已解决。
![image](https://github.com/user-attachments/assets/8c882ca7-d473-4c09-a683-6e50bce43303)

**Comment by festoney8** [comment]
这个背景插件除背景功能外还有一些主题效果，它的一些样式优先级更高，Telegram 插件就无法调色
