### ISSUE TITLE
图片缩放率会使部分图片变糊

### ISSUE THREAD

**Issue by Shironaus** [festoney8/LiteLoaderQQNT-Telegram-Theme#54]
图片缩放率会使部分图片变糊，长图尤为明显，点击图片以图片查看为正常，有什么办法能让消息图片就是以原图显示

**Comment by festoney8** [comment]
目前没有好的解决方法，普通浏览时只会载入缩略图，只有双击查看大图才会从服务器获取原图

缩略图一般比普通浏览时的图片大，主题内的缩放多数不会模糊，但长图由于图片高度限制，官方把缩略图压缩到宽度只有 100px 左右，模糊是不可避免的了
