### ISSUE TITLE
头像置底、连续消息合并、头像浮动等功能在qq重启后不能及时启动

### ISSUE THREAD

**Issue by CPtAu** [festoney8/LiteLoaderQQNT-Telegram-Theme#55]
重启qq后打开一个聊天窗口，必须上拉使聊天界面加载历史消息或者等待一段时间才可使上述功能启用。第一张图是刚重启qq后打开的群聊界面，图二为等待一段时间后功能正常截图
![屏幕截图 2024-10-27 142647](https://github.com/user-attachments/assets/15ad4ae4-2eeb-4270-b3e8-501073c71c1a)
![屏幕截图 2024-10-27 142717](https://github.com/user-attachments/assets/702a03f1-f5aa-4681-9a77-3572b34e2a17)

**Comment by festoney8** [comment]
已在 [v4.5.1](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/releases/tag/v4.5.1) 修复

另，测试时发现偶尔出现消息合并成功但头像没有置底的情况，可能是轻量工具箱的副作用

**Comment by CPtAu** [comment]
我更新后也马上遇到了你说的问题，所以是只能卸载掉轻量工具箱才能彻底解决吗？

**Comment by CPtAu** [comment]
> 已在 [v4.5.1](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/releases/tag/v4.5.1) 修复
> 
> 另，测试时发现偶尔出现消息合并成功但头像没有置底的情况，可能是轻量工具箱的副作用

我更新后也马上遇到了你说的问题，所以是只能卸载掉轻量工具箱才能彻底解决吗？

**Comment by festoney8** [comment]
> > 已在 [v4.5.1](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/releases/tag/v4.5.1) 修复
> > 另，测试时发现偶尔出现消息合并成功但头像没有置底的情况，可能是轻量工具箱的副作用
> 
> 我更新后也马上遇到了你说的问题，所以是只能卸载掉轻量工具箱才能彻底解决吗？

不知道是不是同一现象，在双列模式没有这一问题，在单列模式，每个聊天都是独立窗口时，会影响一下头像位置，在滚动聊天记录后现象消失
