### ISSUE TITLE
不兼容背景插件

### ISSUE THREAD

**Issue by YuYue-Amatsuki** [festoney8/LiteLoaderQQNT-Telegram-Theme#6]
例如我在[背景插件](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin)设置了以网络api的图片作为背景图片不会显示，在设置页面才会正常显示
![image](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/86163024/d6f9f0c2-3ded-4432-a543-7a8d17d64970)
![image](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/86163024/b7d63183-eeda-4332-b650-7ef35c5fb06a)

**Comment by festoney8** [comment]
解决方法：把 [这张全透明图片](https://upload.wikimedia.org/wikipedia/commons/8/89/HD_transparent_picture.png) 下载下来，设置成 Telegram 主题背景图片即可

PS. Telegram主题和背景插件可以同时使用，但主题效果会被影响。背景插件自带一部分主题功能，它会默认添加一套样式（比如背景遮罩、会话列表圆角、用户昵称颜色），同时使用背景插件和Telegram主题会有一些意料之外的样式出现
