### ISSUE TITLE
不兼容Scriptio插件中的hitokoto插件脚本

### ISSUE THREAD

**Issue by YuYue-Amatsuki** [festoney8/LiteLoaderQQNT-Telegram-Theme#7]
当使用[Scriptio](https://github.com/PRO-2684/Scriptio)插件加载[hitokoto](https://github.com/PRO-2684/Scriptio-user-scripts/#hitokoto)插件脚本时，主题自带的文本覆盖了插件脚本在输入框占位符上显示的一言，希望添加一个按钮可关闭主题的输入框占位符上的文本
![hitokoto](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/86163024/cb00b67d-8c7a-4013-a2fd-8ee96eb9eafc)
![image](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/86163024/60c7be18-cad3-4c4c-8f3c-26ab608451c0)

**Comment by festoney8** [comment]
这句自带的文本是高仿 Telegram 的特性之一，如果你希望使用hitokoto脚本，可以（在本地 或 fork项目）注释掉 telegram.scss 文件这四行，使用 [scss to css](https://marketplace.visualstudio.com/items?itemName=yutent.scss-to-css) 工具重新生成 telegram.css 文件，重启QQ即可
https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/blob/8d2d0bebe9ca954c63f4d015384261f5140c41f9/src/style/telegram.scss#L555-L558

使用hitokoto的用户并不多，所以不考虑新增开关按钮

最终效果：
![image](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/36254268/6e70941f-4493-4449-8f1a-7c3d17834d37)
