### ISSUE TITLE
聊天界面头像消息错位bug

### ISSUE THREAD

**Issue by YuYue-Amatsuki** [festoney8/LiteLoaderQQNT-Telegram-Theme#8]
如图所示
![Image_1707670460015.jpg](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/86163024/caeecfa4-cde1-44fb-b7eb-2111e5f38a2d)

**Comment by festoney8** [comment]
是不是启用了轻量工具箱的「头像置底、头像浮动、连续消息合并」其中某项功能？

**Comment by YuYue-Amatsuki** [comment]
> 是不是启用了轻量工具箱的「头像置底、头像浮动、连续消息合并」其中某项功能？

并没有，启用轻量工具箱的功能反而无法显示头像

**Comment by festoney8** [comment]
需要测试一下只保留Telegram主题开启时，会不会出现这一现象，如果现象消失，说明是插件冲突造成的
